Implemented initial version of login core functionality
AndreyWeber/fes-react-course-marksboard pull request #6
Opened 2016-11-22 09:20 UTC by AndreyWeber

#2 Implementation.

Stuck on adding blocking wait during user login.

2016-11-24 09:32 UTC, AndreyWeber commented
Implements #2 and #5

2016-11-24 11:23 UTC, krambertech requested changes

2016-11-24 11:23 UTC, krambertech commented on .eslintrc.js
>          "quotes": ["error", "single", { "avoidEscape": true }],
Maybe we need to extend from airbnb config? We will have all latest rules then.

You can apply this:
https://gist.github.com/krambertech/490f27b35d98f7d3954212d55074a547

I'll add a separate task for this

2016-11-24 11:23 UTC, krambertech commented on public/static/config.js
>  var APP_CONFIG = {
It's better to create sample config than add placeholders. You can create sample table for that and its id to config

2016-11-24 11:23 UTC, krambertech commented on src/actions/index.js
> +    getStudentTotalScore
We can reduce it on the client. I think its better to get all records and then with the magic of selectors retrieve anything from it

2016-11-24 11:23 UTC, krambertech commented on src/actions/index.js
> +export const userLoginFailure = (login, error) => ({
No need to have separate actions for everything. You can write dispatch directly in your main action creator

2016-11-24 11:23 UTC, krambertech commented on src/api/index.js
> +const REVIEWS_TAB = 'Reviews';
Better to have an object with tabs, not separate variables

2016-11-24 11:23 UTC, krambertech commented on src/api/index.js
> +                ranges: [`${STUDENTS_TAB}!1:1`, `${STUDENTS_TAB}!2:1000`],
Hardcoded number is bad. Let's move it somewhere in the const

2016-11-24 11:23 UTC, krambertech commented on src/selectors/login.js
> +export const getLoggedIn = createSelector(
isLoggedIn

2016-11-24 11:23 UTC, krambertech commented on src/selectors/login.js
> +export const getLoggingIn = createSelector(
isLoggingIn

2016-11-24 11:23 UTC, krambertech commented on src/routes.jsx
> +        <Route component={LoginPage} path="login" />
Better to write path first. It's easier to scan routes

2016-11-24 11:23 UTC, krambertech commented on src/reducers/user.js
> +        case TOTAL_SCORE_REQUEST: {
Why do you have everything in one reducer?

2016-11-24 11:23 UTC, krambertech commented on src/reducers/login.js
> +            user(state, action);
What is this and why is it here?

2016-11-24 11:23 UTC, krambertech commented on src/containers/LoginPage.jsx
> +    handleClick = login => this.props.userLogin(login);
Why do you need this handler, it's useless

2016-11-24 11:23 UTC, krambertech commented on src/containers/LoginPage.jsx
> +            <Login onClick={this.handleClick} />
Why onClick? It is better to have properly named callbacks. They need to express what is going on. 

For example in this case it's better to name it onLogin or smthng

2016-11-24 11:23 UTC, krambertech commented on src/containers/LoginPage.jsx
> +            return;
Why do you need it?

2016-11-24 11:23 UTC, krambertech commented on src/components/TotalScore.less
> +}
Empty line

2016-11-24 11:26 UTC, krambertech commented
User needs to login not by its user name but by unique generated key.

2016-11-24 11:26 UTC, krambertech commented
Also, enter does not work for login

2016-11-27 12:45 UTC, AndreyWeber commented on public/static/config.js
>  var APP_CONFIG = {
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/actions/index.js
> +    getStudentTotalScore
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/actions/index.js
> +export const userLoginFailure = (login, error) => ({
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/api/index.js
> +const REVIEWS_TAB = 'Reviews';
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/api/index.js
> +                ranges: [`${STUDENTS_TAB}!1:1`, `${STUDENTS_TAB}!2:1000`],
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/selectors/login.js
> +export const getLoggedIn = createSelector(
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/selectors/login.js
> +export const getLoggingIn = createSelector(
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/routes.jsx
> +        <Route component={LoginPage} path="login" />
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/reducers/user.js
> +        case TOTAL_SCORE_REQUEST: {
Done

2016-11-27 12:45 UTC, AndreyWeber commented on src/reducers/login.js
> +            user(state, action);
Done

2016-11-27 12:46 UTC, AndreyWeber commented on src/containers/LoginPage.jsx
> +            return;
Strange moment. Should be OK after the next commit. 'if' required to skip route.replace in case if user still logging in.

2016-11-27 12:46 UTC, AndreyWeber commented on src/containers/LoginPage.jsx
> +    handleClick = login => this.props.userLogin(login);
Done

2016-11-27 12:46 UTC, AndreyWeber commented on src/containers/LoginPage.jsx
> +            <Login onClick={this.handleClick} />
Done

2016-11-27 12:46 UTC, AndreyWeber commented on src/components/TotalScore.less
> +}
Fixed

2016-11-29 18:28 UTC, AndreyWeber commented
Implements #8

2016-12-06 10:24 UTC, merged